print ("\e[0;30m Color: Black  Regular Colors")
print ("\e[0;31m Color: Red    Regular Colors")
print ("\e[0;32m Color: Green  Regular Colors")
print ("\e[0;33m Color: Yellow Regular Colors")
print ("\e[0;34m Color: Blue   Regular Colors")
print ("\e[0;35m Color: Purple Regular Colors")
print ("\e[0;36m Color: Cyan   Regular Colors")
print ("\e[0;37m Color: White  Regular Colors")

print ("\e[1;30m Color: Black    Bold")
print ("\e[1;31m Color: Red      Bold")
print ("\e[1;32m Color: Green    Bold")
print ("\e[1;33m Color: Yellow   Bold")
print ("\e[1;34m Color: Blue     Bold")
print ("\e[1;35m Color: Purple   Bold")
print ("\e[1;36m Color: Cyan     Bold")
print ("\e[1;37m Color: White    Bold")
print ("\e[1m    Color: No Color Bold")

print ("\e[4;30m Color: Black    Underline")
print ("\e[4;31m Color: Red      Underline")
print ("\e[4;32m Color: Green    Underline")
print ("\e[4;33m Color: Yellow   Underline")
print ("\e[4;34m Color: Blue     Underline")
print ("\e[4;35m Color: Purple   Underline")
print ("\e[4;36m Color: Cyan     Underline")
print ("\e[4;37m Color: White    Underline")
print ("\e[4m    Color: No Color Underline")
       
print ("\e[40m Color: Black  Background")
print ("\e[41m Color: Red    Background")
print ("\e[42m Color: Green  Background")
print ("\e[43m Color: Yellow Background")
print ("\e[44m Color: Blue   Background")
print ("\e[45m Color: Purple Background")
print ("\e[46m Color: Cyan   Background")
print ("\e[47m Color: White  Background")
       
print ("\e[K Color:No Color Expand Background Horizontally")

print ("\e[0;90m Color: Black  High Intensty")
print ("\e[0;91m Color: Red    High Intensty")
print ("\e[0;92m Color: Green  High Intensty")
print ("\e[0;93m Color: Yellow High Intensty")
print ("\e[0;94m Color: Blue   High Intensty")
print ("\e[0;95m Color: Purple High Intensty")
print ("\e[0;96m Color: Cyan   High Intensty")
print ("\e[0;97m Color: White  High Intensty")

print ("\e[1;90m Color: Black  Bold High Intensty")
print ("\e[1;91m Color: Red    Bold High Intensty")
print ("\e[1;92m Color: Green  Bold High Intensty")
print ("\e[1;93m Color: Yellow Bold High Intensty")
print ("\e[1;94m Color: Blue   Bold High Intensty")
print ("\e[1;95m Color: Purple Bold High Intensty")
print ("\e[1;96m Color: Cyan   Bold High Intensty")
print ("\e[1;97m Color: White  Bold High Intensty")
       
print ("\e[0;100m Color:Black  High Intensty backgrounds")
print ("\e[0;101m Color:Red    High Intensty backgrounds")
print ("\e[0;102m Color:Green  High Intensty backgrounds")
print ("\e[0;103m Color:Yellow High Intensty backgrounds")
print ("\e[0;104m Color:Blue   High Intensty backgrounds")
print ("\e[0;105m Color:Purple High Intensty backgrounds")
print ("\e[0;106m Color:Cyan   High Intensty backgrounds")
print ("\e[0;107m Color:White  High Intensty backgrounds")
       
print ("\e[0m Color: Reset")
